#!/usr/bin/env bash
# git-workflow.sh — Automatización de setup git + commit atómico
# Basado en: specs/done/dark-mode.md (arquitectura en capas, contratos, flujo)
#
# Capas:
#   Bootstrap  → git init, .gitignore, estructura ramas
#   Provider   → gh repo create, remote config
#   Commit     → stage, commit, push
#   Post       → auto-sync, archivar spec, registro
#
# Uso:
#   ./scripts/git-workflow.sh setup    ← para repo nuevo
#   ./scripts/git-workflow.sh commit   ← solo commit+post (uso diario)
#   ./scripts/git-workflow.sh          ← flujo completo interactivo

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; }
info() { echo -e "${CYAN}[i]${NC} $1"; }

ask_yn() {
  local prompt="$1 (y/n): "
  local ans
  while true; do
    read -r -p "$prompt" ans
    case "$ans" in
      [Yy]*) return 0 ;;
      [Nn]*) return 1 ;;
      *) echo "  Responde y o n." ;;
    esac
  done
}

ask_choice() {
  local prompt="$1"
  shift
  local options=("$@")
  echo "$prompt"
  select opt in "${options[@]}"; do
    if [[ -n "$opt" ]]; then
      echo "$opt"
      return
    fi
  done
}

###########################################################
# PASO 1: git init + .gitignore
###########################################################
bootstrap_git() {
  if [[ -d .git ]]; then
    warn ".git ya existe — saltando git init"
  else
    git init
    log "git init ok"
  fi

  if [[ ! -f .gitignore ]]; then
    echo "# Autogenerated by git-workflow.sh" > .gitignore
    log ".gitignore creado"
  fi

  info "Patrones para .gitignore (vacío = saltar)"
  while true; do
    read -r -p "  Patrón (ENTER para terminar): " pat
    [[ -z "$pat" ]] && break
    if ! grep -qF "$pat" .gitignore 2>/dev/null; then
      echo "$pat" >> .gitignore
      log "Añadido: $pat"
    else
      warn "Ya existe: $pat"
    fi
  done

  # Patrones comunes si no existen
  for common in "node_modules/" "dist/" ".env" "*.log"; do
    if ! grep -qF "$common" .gitignore 2>/dev/null; then
      echo "$common" >> .gitignore
    fi
  done
  log ".gitignore completado"
}

###########################################################
# PASO 2: Ramas / estructura
###########################################################
setup_branches() {
  local current_branch
  current_branch=$(git branch --show-current 2>/dev/null || echo "")

  if ask_yn "¿Crear rama develop?"; then
    if git show-ref --verify --quiet refs/heads/develop; then
      warn "develop ya existe"
    else
      git branch develop
      log "Rama develop creada"
    fi
  fi

  while ask_yn "¿Crear rama adicional?"; do
    read -r -p "  Nombre de rama: " branch_name
    if [[ -z "$branch_name" ]]; then
      warn "Nombre vacío — saltando"
      continue
    fi
    if git show-ref --verify --quiet "refs/heads/$branch_name"; then
      warn "Rama $branch_name ya existe"
    else
      git branch "$branch_name"
      log "Rama $branch_name creada"
    fi
  done

  # Mostrar estructura actual
  echo ""
  info "Estructura de ramas:"
  git branch -a | head -20
  echo ""

  if [[ -z "$current_branch" || "$current_branch" == "main" ]]; then
    :
  fi
}

###########################################################
# PASO 3: gh repo create + remote
###########################################################
setup_remote() {
  if git remote get-url origin &>/dev/null; then
    warn "Remote 'origin' ya configurado: $(git remote get-url origin)"
    if ask_yn "¿Reemplazar?"; then
      git remote remove origin
    else
      return
    fi
  fi

  if ! command -v gh &>/dev/null; then
    err "gh CLI no instalada — saltando gh repo create"
    return
  fi

  if gh repo view --json name &>/dev/null 2>&1; then
    warn "Repo ya existe en GitHub"
  else
    local repo_visibility
    repo_visibility=$(ask_choice "Visibilidad del repo:" "public" "private")
    local repo_name
    read -r -p "  Nombre del repo (ENTER = nombre del directorio): " repo_name
    if [[ -z "$repo_name" ]]; then
      repo_name=$(basename "$(pwd)")
    fi
    gh repo create "$repo_name" "--$repo_visibility" --source=. --remote=origin --push
    log "gh repo create: $repo_name ($repo_visibility)"
  fi

  # Asegurar remote configurado
  if ! git remote get-url origin &>/dev/null; then
    read -r -p "  URL del remote (git@github.com:user/repo.git): " remote_url
    if [[ -n "$remote_url" ]]; then
      git remote add origin "$remote_url"
      log "Remote origin configurado"
    fi
  fi
}

###########################################################
# PASO 4: Stage + commit atómico
###########################################################
do_commit() {
  info "Archivos sin stage:"
  git status --short | head -30
  echo ""

  local scope=""
  read -r -p "  Scope del cambio (ej: dark-mode, layout, vacío=ninguno): " scope

  local msg=""
  local suggested=""
  if [[ -n "$scope" ]]; then
    suggested="feat: implement $scope"
  else
    # Detectar tipo de cambio
    if git diff --cached --stat &>/dev/null; then
      suggested=$(git diff --cached --stat | head -1 | sed 's/.*\///' | sed 's/\..*//')
      suggested="feat: update $suggested"
    else
      suggested="feat: update"
    fi
  fi

  if [[ -z "$scope" ]]; then
    suggested="feat: update $(date +%Y%m%d)"
  fi

  info "Mensaje sugerido: '$suggested'"
  if ask_yn "¿Usar mensaje sugerido?"; then
    msg="$suggested"
  else
    echo "  Escribe el mensaje de commit (ENTER en blanco para cancelar):"
    read -r -p "  > " user_msg
    if [[ -z "$user_msg" ]]; then
      err "Commit cancelado"
      return 1
    fi
    msg="$user_msg"
  fi

  # Stage automático
  info "Archivos a incluir en stage:"
  git status --short
  echo ""
  if ask_yn "¿Hacer stage de todos los cambios?"; then
    git add -A
    log "Stage completo"
  else
    echo "  Usa 'git add <file>' manualmente, luego presiona ENTER para continuar..."
    read -r -s
    if [[ -z "$(git diff --cached --stat)" ]]; then
      err "No hay archivos en stage — abortando commit"
      return 1
    fi
  fi

  git commit -m "$msg"
  log "Commit creado: $(git rev-parse --short HEAD)"

  if ask_yn "¿Hacer push ahora?"; then
    local branch
    branch=$(git branch --show-current)
    if git remote get-url origin &>/dev/null; then
      git push -u origin "$branch"
      log "Push a origin/$branch"
    else
      err "No hay remote configurado — push omitido"
    fi
  fi

  echo "$msg"
}

###########################################################
# PASO 5: Post-config — auto-sync
###########################################################
post_config() {
  info "Post-config: detector de cambios automático"
  warn "El auto-sync requiere ejecución manual. Opciones:"
  echo "  1) Crear script post-commit hook"
  echo "  2) Añadir alias 'git sync' al repo"
  echo "  3) Saltar"

  local choice
  read -r -p "  Opción (1/2/3): " choice
  case "$choice" in
    1)
      local hook=".git/hooks/post-commit"
      cat > "$hook" << 'HOOK'
#!/usr/bin/env bash
# Post-commit hook: detecta cambios no commiteados tras commit
if [[ -n "$(git status --porcelain)" ]]; then
  echo "[post-commit] ⚠  Quedan cambios sin commit:"
  git status --short
fi
HOOK
      chmod +x "$hook"
      log "post-commit hook instalado"
      ;;
    2)
      git config alias.sync "!f() { git add -A && git commit -m \"sync: $(date +%Y%m%d-%H%M)\" && git push; }; f"
      log "Alias 'git sync' configurado"
      ;;
    3)
      warn "Post-config omitido"
      ;;
  esac
}

###########################################################
# PASO 6: Preguntar mensaje de commit (ya integrado en do_commit)
# PASO 7: Archivar spec
###########################################################
archive_spec() {
  local done_dir="specs/done"
  local archived_dir="specs/archived"

  if [[ ! -d "$done_dir" ]]; then
    info "No existe specs/done — omitiendo archive"
    return
  fi

  local specs=()
  while IFS= read -r -d '' f; do
    specs+=("$(basename "$f")")
  done < <(find "$done_dir" -maxdepth 1 -name "*.md" -print0 2>/dev/null)

  if [[ ${#specs[@]} -eq 0 ]]; then
    info "No hay specs en done/ — omitiendo archive"
    return
  fi

  echo ""
  info "Specs en done/ a archivar:"
  for s in "${specs[@]}"; do
    echo "  - $s"
  done
  echo ""

  if ask_yn "¿Mover todos los specs de done/ a archived/?"; then
    mkdir -p "$archived_dir"
    for s in "${specs[@]}"; do
      mv "$done_dir/$s" "$archived_dir/$s"
      log "Archivado: $s → $archived_dir/"
    done
  else
    for s in "${specs[@]}"; do
      if ask_yn "¿Archivar $s?"; then
        mkdir -p "$archived_dir"
        mv "$done_dir/$s" "$archived_dir/$s"
        log "Archivado: $s"
      fi
    done
  fi
}

###########################################################
# PASO 8: Crear registro de commit
###########################################################
create_commit_record() {
  local msg="${1:-}"
  local commit_sha
  commit_sha=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
  local commit_date
  commit_date=$(git log -1 --format=%ci 2>/dev/null || date "+%Y-%m-%d %H:%M:%S %z")
  local commit_author
  commit_author=$(git log -1 --format="%an <%ae>" 2>/dev/null || git config user.name 2>/dev/null || echo "unknown")
  local branch
  branch=$(git branch --show-current 2>/dev/null || echo "unknown")

  local record_file="specs/commits/${commit_sha}.md"
  mkdir -p "specs/commits"

  cat > "$record_file" << EOF
# Commit: ${commit_sha}

| Campo | Valor |
|---|---|
| **Fecha** | ${commit_date} |
| **Autor** | ${commit_author} |
| **Rama** | ${branch} |
| **Mensaje** | ${msg} |
| **Hash** | ${commit_sha} |

## Archivos modificados

\`\`\`
$(git diff --stat HEAD~1..HEAD 2>/dev/null || git show --stat --oneline HEAD 2>/dev/null || echo "(primer commit)")
\`\`\`

## Archivos creados

$(git diff --diff-filter=A HEAD~1..HEAD --name-only 2>/dev/null | sed 's/^/- `/' | sed 's/$/`/' || echo "(primer commit)")

## Archivos eliminados o renombrados

$(git diff --diff-filter=DR HEAD~1..HEAD --name-only 2>/dev/null | sed 's/^/- `/' | sed 's/$/`/' || echo "- Ninguno")

## Notas

- Spec archivado: \`specs/archived/\`
EOF

  log "Registro de commit: $record_file"
}

###########################################################
# MAIN: orquestador
###########################################################
main() {
  local mode="${1:-full}"

  echo ""
  echo "=============================================="
  echo "  git-workflow.sh — Git automation"
  echo "=============================================="
  echo ""

  case "$mode" in
    setup)
      bootstrap_git
      setup_branches
      setup_remote
      ;;
    commit)
      local msg
      msg=$(do_commit) || exit 1
      archive_spec
      create_commit_record "$msg"
      post_config
      ;;
    full)
      if [[ -d .git ]]; then
        info "Repo existente detectado — saltando bootstrap"
        info "¿Quieres configurar remote o solo commitear?"
        local action
        action=$(ask_choice "Acción:" "Solo commit" "Setup completo")
        if [[ "$action" == "Setup completo" ]]; then
          setup_remote
        fi
      else
        bootstrap_git
        setup_branches
        setup_remote
      fi
      local msg
      msg=$(do_commit) || exit 1
      archive_spec
      create_commit_record "$msg"
      post_config
      ;;
    *)
      echo "Uso: $0 {setup|commit|full}"
      echo "  setup   — git init + .gitignore + ramas + gh repo"
      echo "  commit  — stage + commit + push + archivar + registro"
      echo "  full    — flujo completo (default)"
      exit 1
      ;;
  esac

  echo ""
  log "Flujo completado."
}

main "$@"
